SET DATABASE COLLATION "Latin1_General"
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE CACHED TABLE "Game"("Title" VARCHAR(255) NOT NULL,"GenreID" INTEGER NOT NULL,"ReleaseYear" DATE NOT NULL,"PubID" INTEGER,"SystemID" INTEGER,"ProdID" INTEGER NOT NULL,"SeriesID" INTEGER NOT NULL,"SalesNumbers(M)" DECIMAL(100) NOT NULL,PRIMARY KEY("Title","ProdID"))
CREATE CACHED TABLE "Producer"("Name" VARCHAR(255) NOT NULL PRIMARY KEY,"FoundDate" DATE NOT NULL,"ClosureDate" DATE,"ProdID" INTEGER)
CREATE CACHED TABLE "Publisher"("PubID" INTEGER,"Name" VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,"FoundDate" DATE NOT NULL,"ClosureDate" DATE)
CREATE CACHED TABLE "System"("SystemID" INTEGER NOT NULL,"SystemName" VARCHAR(255) NOT NULL PRIMARY KEY,"SysReleaseDate" DATE NOT NULL,"DiscontinueDate" DATE,"ConsoleDeveloper" VARCHAR(255) NOT NULL)
CREATE CACHED TABLE "Genre"("GenreName" VARCHAR_IGNORECASE(255) NOT NULL PRIMARY KEY,"GenreID" VARCHAR(50),"YearCreated" DATE)
CREATE CACHED TABLE "Series"("SeriesID" INTEGER NOT NULL,"SeriesName" VARCHAR(50) NOT NULL PRIMARY KEY,"Entries" INTEGER NOT NULL,"DiscontinueDate" DATE,"ReleaseDate" DATE NOT NULL)
CREATE USER SA PASSWORD ""
GRANT DBA TO SA
SET WRITE_DELAY 60
